name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          docker build . --file Dockerfile --tag php-web
          docker login --username benjaminshi --password Aa%123qweasd
          docker image tag php-web benjaminshi/php-web:latest
          docker image tag php-web benjaminshi/php-web:v1.1.$(date +%s)
          docker image tag php-web benjaminshi/php-web:v1.1
          docker image push --all-tags benjaminshi/php-web
          
